# Generated by Django 3.2.3 on 2021-06-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogData',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.CharField(editable=False, max_length=70, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('username', models.CharField(max_length=30)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('image_url', models.CharField(default='profile.png', max_length=60)),
            ],
            options={
                'db_table': 'registered_user',
            },
        ),
        migrations.CreateModel(
            name='Bloggers',
            fields=[
                ('id', models.CharField(editable=False, max_length=70, primary_key=True, serialize=False, unique=True)),
                ('uuid_blog_data', models.CharField(max_length=90)),
                ('title_of_blog', models.TextField(max_length=40000)),
                ('blog_data', models.TextField(max_length=40000)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date joined')),
            ],
        ),
    ]
